# ============================================================================
# Module: Kitty / Fonts
# Project: Dotfiles
# ----------------------------------------------------------------------------
# Requiere FiraCode Nerd Font y Noto Sans CJK.
# ============================================================================

# ---- Familia ----
font_family      family="FiraCode Nerd Font Mono" style=Regular
bold_font        family="FiraCode Nerd Font Mono" style=SemiBold
italic_font      auto
bold_italic_font auto

font_size 11.0

# ---- Japones (CJK) ----
symbol_map U+3000-U+303F,U+3040-U+309F,U+30A0-U+30FF,U+31F0-U+31FF,U+FF00-U+FFEF Noto Sans CJK JP
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF Noto Sans CJK JP

# ---- Ajustes ----
disable_ligatures         cursor
modify_font               cell_height 105%
text_composition_strategy platform
undercurl_style           thin-sparse
