# ============================================================================
# Module: Kitty / Keys
# Project: Dotfiles
# ----------------------------------------------------------------------------
# Atajos propios. Se suman a los de fabrica de kitty.
# ============================================================================

kitty_mod ctrl+shift

# ---- Config ----
map kitty_mod+f5 load_config_file

# ---- Splits ----
map kitty_mod+enter     launch --location=hsplit --cwd=current
map kitty_mod+backslash launch --location=vsplit --cwd=current
map kitty_mod+w         close_window

map kitty_mod+h neighboring_window left
map kitty_mod+j neighboring_window down
map kitty_mod+k neighboring_window up
map kitty_mod+l neighboring_window right

map kitty_mod+left  resize_window narrower
map kitty_mod+right resize_window wider
map kitty_mod+up    resize_window taller
map kitty_mod+down  resize_window shorter
map kitty_mod+home  resize_window reset

# ---- Tabs ----
map kitty_mod+t    new_tab_with_cwd
map kitty_mod+q    close_tab
map ctrl+tab       next_tab
map ctrl+shift+tab previous_tab

# ---- Fuente ----
map kitty_mod+equal     change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0

# ---- Portapapeles ----
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

# ---- Scrollback ----
map kitty_mod+g show_scrollback
map kitty_mod+o show_last_command_output

# ---- Kittens ----
map kitty_mod+u   kitten unicode_input
map kitty_mod+e   open_url_with_hints
map kitty_mod+p>f kitten hints --type path --program -
map kitty_mod+p>l kitten hints --type line --program -
