# ============================================================================
# Module: Kitty
# Project: Dotfiles
# ----------------------------------------------------------------------------
# Archivo principal. Solo importa modulos.
#
# Cambiar de tema:
#   ln -sfn themes/<nombre>.conf ~/.config/kitty/theme.conf
# ============================================================================

include fonts.conf
include window.conf
include keys.conf
include theme.conf
